name: TestDotNet

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]
  
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
   - uses: action/checkout@main
  
  steps:
   - name: Set up .NET Core
     uses: actions/setup-dotnet@v1
     with:
      dotnet-version: '2.1.804'
     
