name: test-workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run build command
    - run: echo "Hello $GITHUB_ACTOR!"
    
  test-job1: 
    runs-on: windows-latest
    steps: 
    - name: Run test1
      uses: actions/checkout@v2
    - run: echo "This job tests something"
  
